apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: techies-apigateway
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - image: "jesulink2514/techies.apigateway"
          imagePullPolicy: Always
          name: apigateway
          ports:
            - containerPort: 80
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: techies-gateway-config
        - image: jaegertracing/jaeger-agent
          name: jaeger-agent
          ports:
          - containerPort: 5775
            protocol: UDP
          - containerPort: 6831
            protocol: UDP
          - containerPort: 6832
            protocol: UDP
          - containerPort: 5778
            protocol: TCP
          args: ["--collector.host-port=jaeger-collector.default.svc.cluster.local:14267"]
---
apiVersion: v1
kind: Service
metadata:
  name: techies-apigateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: tcp-80
  - port: 443
    name: tcp-443
  selector:
    app: apigateway
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: techies-gateway-config
  namespace: default
data:  
  Swagger__Host: 'microtechies.eastus.cloudapp.azure.com'
  Swagger__Schema: 'HTTP'
---