apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: techies-stats
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: client-stats
    spec:
      containers:
        - image: "jesulink2514/techies.client.stats.api"
          imagePullPolicy: Always
          name: client-stats
          ports:
            - containerPort: 80
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: techies-stats-config
          livenessProbe:
            httpGet:
                path: /health
                port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
        - image: jaegertracing/jaeger-agent
          name: jaeger-agent
          ports:
          - containerPort: 5775
            protocol: UDP
          - containerPort: 6831
            protocol: UDP
          - containerPort: 6832
            protocol: UDP
          - containerPort: 5778
            protocol: TCP
          args: ["--collector.host-port=jaeger-collector.default.svc.cluster.local:14267"]
---
apiVersion: v1
kind: Service
metadata:
  name: techies-stats
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: tcp-80
  - port: 443
    name: tcp-443
  selector:
    app: client-stats
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: techies-stats-config
  namespace: default
data:  
  RabbitMq__HostName: 'rabbit-rabbitmq.default.svc.cluster.local'
  RabbitMq__User: 'ruser'
  RabbitMq__Password: 'r123456'  
  ElasticSearch__Host: 'http://elasticsearch-master.default:9200'
  ElasticSearch__User: ''
  ElasticSearch__Password: ''
---